language: python
python:
- "3.8"
# setup environment
env:
- DJANGO_VERSION=3.1.1
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python manage.py runserver
