language: node_js
python:
  - "3.8"
  
services: # => 3
      - mysql
      
env: # => 4
      -DJANGO=3.1 DB=mysql
    before_script: # => 6
      - mysql -e 'CREATE DATABASE djangodb;' -u root
    script: # => 7
      - python manage.py runserver
