language: python

python:
 - "3.8"

services: postgresql

before_install:
  - sudo apt-get install python3-dev default-libmysqlclient-dev build-essential

install:
 - pip install -r requirements.txt
 - pip install mysqlclient==2.0.1



script: 
 - python manage.py check
