language: python

python:
 - "3.8"

services: postgresql


install:
 - pip install -r requirements.txt

before_script:
  - psql -c 'CREATE DATABASE djangodb;' -U postgres

script: 
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test
