# Generated by Django 3.1.1 on 2020-09-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=2)),
                ('sfname', models.CharField(max_length=15)),
                ('slname', models.CharField(max_length=15)),
                ('gfname', models.CharField(max_length=15)),
                ('glname', models.CharField(max_length=15)),
                ('semail', models.EmailField(max_length=254)),
                ('scontact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
